services:
  frontend:
    image: atria-frontend:latest
    container_name: atria-frontend
    restart: unless-stopped
    networks:
      - proxy-network

# Connect to the same Docker network as Nginx Proxy Manager
networks:
  proxy-network:
    external: true
    name: nginx-proxy-manager_default
